### ISSUE TITLE
Two off by one errors ?

### ISSUE THREAD

**Issue by dcb314** [smbolton/whysynth#6]
1.

[common_data.c:473]: (error) Width 180 given in format string (no. 1) is larger than destination buffer 'buf2[180]', use %179s to prevent overflowing it.

Source code is

```
} else if (sscanf(buf, " comment %180s", buf2) == 1) {
```

2.

[gui_data.c:700]: (error) Width 90 given in format string (no. 1) is larger than destination buffer 'buf2[90]', use %89s to prevent overflowing it.

```
if (sscanf(buf, " name %90s", buf2) == 1) {
```

**Comment by smbolton** [comment]
Thanks, @dcb314!
